---
title: "Resources"
author: "Nirvikalpa Projects"
date: "3 June 2018"
output: html_document
runtime: shiny
---

**What the heck is a Deep Learning ?**

Deep learning is a machine learning technique that teaches computers to do what comes naturally to humans: learn by example. Deep learning is a key technology behind sel-driven car, consumer devices like phones, tablets, TVs, and hands-free speakers. Deep learning is getting lots of attention lately and for good reason. It's achieving results that were not possible before.

In deep learning, a computer model learns to perform classification tasks directly from images, text, or sound. Deep learning models can achieve state-of-the-art accuracy, sometimes exceeding human-level performance. Models are trained by using a large set of labeled data and neural network architectures that contain many layers.

**What is a pre-trained model?**

A pre-trained model is one which has been previously trained on a similar task other than the current one. It has two parts - model architecture and model weights. 

The most popular ones are VGG16 and VGG19, RESNET50, inception_v3 and densenet.


**What are the benefits and tradeoffs?**

A pre-trained model, while not 100% accurate still provides a very useful starting point because the features learned while training on the former task are useful for the new task.
Tranfering the learnings from the pre-trained model reduces the computational cost from developing a neural net from scratch. 

_____
  
Here are a list of tutorials and papers about Deep Learning & Image Classification:
  
1. [Keras interface with R, keras functions](https://keras.rstudio.com/reference/index.html)
1. [Amazing Introduction by Siraj Raval, Introduction to Deep Learning](https://www.youtube.com/watch?v=_qjNH1rDLm0&t=32s)
2. [DataCamp's Keras Deep Learning R Tutorial](https://www.datacamp.com/community/tutorials/keras-r-deep-learning)
3. [Deep Learning using Tensorflow, Edureka](https://www.youtube.com/watch?v=yX8KuPZCAMo&t=566s)
4. [CNN Architecture,Edureka](https://www.youtube.com/watch?v=umGJ30-15_A&t=1149s)
5. [Keras Tutorial: Using pre-trained Imagenet models](http://www.learnopencv.com/keras-tutorial-using-pre-trained-imagenet-models/)
6. [Transfer learning & The art of using Pre-trained Models in Deep Learning](https://www.analyticsvidhya.com/blog/2017/06/transfer-learning-the-art-of-fine-tuning-a-pre-trained-model/)
7. [useR 2016 Machine Learning Algorithmic Deep Dive Tutorial](https://github.com/ledell/useR-machine-learning-tutorial/blob/master/deep-neural-networks.ipynb)

